name: Build Web

on:
  workflow_call:

jobs:
  build_web:
    name: Build Web
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          npm ci --prefix client
          npm run webpack --prefix client
        name: Build Web
      
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          retention-days: 1
          path: client/dist
