name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  run_tests:
    uses: ./.github/workflows/tests.yml
    name: Run Tests

  build_web:
    uses: ./.github/workflows/build_web.yml
    name: Build Web
  
  release_gh:
    name: Release to GitHub Releases
    needs: [run_tests, build_web]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - run: |
          TAG=$GITHUB_REF_NAME-${GITHUB_SHA:0:7}
          gh release create $TAG --repo $GITHUB_REPOSITORY
          tar -cf dist.tar dist
          gh release upload $TAG dist.tar --repo $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Create Release
