name: Tests

on:
  pull_request:
    branches: [ "master" ]
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Eval Tests
        run: |
            python3 server/src/evaluation/eval_test.py
