name: Tests

on:
  pull_request:
    branches: [ "master" ]
  workflow_call:

jobs:
  tests:
    name: Run Tests
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          ls -lia
          TAG=v0-$(date '+%Y%m%d.%H%M%S')
          echo $TAG
        name: List Files
