name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    name: Run tests
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          ls -lia
        name: List Files
